![Logo ITQ](./img/logoitqv1.jpg)

Septimo Programa en Python

# Python 1, Pandas 1

![Logo Python](./img/python_logo.png)

* Nombre: *Christian Zumárraga*
* Fecha : **8-07-2026**
* Repositorio: *[Link del repositorio de GitHub](https://github.com/Crishito/machine12026/blob/main/practicas/Python_Funciones.ipynb)*

# Pandas

* Librería (de facto estándar) para estructurar datos tabulares
* Multivariable (string, int, float, bool…)
* Dos clases:
  * Series (1 dimensión)
  * DataFrames (2+ dimensiones)

In [104]:
# librería externa
import pandas as pd
from pandas import Series, DataFrame

In [105]:
pd.__version__

'3.0.3'

# Series

* Datos unidimensionales (similar a NumPy)
* Elementos + índices modificables

In [106]:
# Creación de una Serie de Pandas
countries = pd.Series(['Spain', 'Andorra', 'Gibraltar', 'Portugal', 'France'])
print(countries)

0        Spain
1      Andorra
2    Gibraltar
3     Portugal
4       France
dtype: str

In [107]:
# Creación de una Serie especificando un índice personalizado
# range(10, 60, 10) genera: [10, 20, 30, 40, 50]
countries = pd.Series(['Spain', 'Andorra', 'Gibraltar', 'Portugal', 'France'], 
                      index=range(10, 60, 10))
print(countries)

10        Spain
20      Andorra
30    Gibraltar
40     Portugal
50       France
dtype: str

In [108]:
# Los índices pueden ser de más tipos (etiquetas de texto)
football_cities = pd.Series(['Barcelona', 'Madrid', 'Valencia', 'Sevilla'],
                            index=['a', 'b', 'c', 'd'])
print(football_cities)

a    Barcelona
b       Madrid
c     Valencia
d      Sevilla
dtype: str

In [109]:
# Atributos
football_cities.name = 'Ciudades con dos equipos en primera' # nombrar la Serie
football_cities.index.name = 'Id' # Describir los índices
print(football_cities)

Id
a    Barcelona
b       Madrid
c     Valencia
d      Sevilla
Name: Ciudades con dos equipos en primera, dtype: str

In [110]:
# Acceso a elementos en la Serie
# acceso por posición usando iloc (forma recomendada)
print(football_cities.iloc[2])

# acceso a través del índice semántico (etiqueta)
print(football_cities['c'])

# Verificación de igualdad entre ambos métodos de acceso
print(football_cities['c'] == football_cities.iloc[2])

Valencia
Valencia
True

# Tratamiento similar a ndarra

In [111]:
# múltiple recolección de elementos
# acceso múltiple usando etiquetas del índice
print(football_cities.loc[['a', 'c']])

# acceso múltiple usando posiciones
print(football_cities.iloc[[0, 3]])

Id
a    Barcelona
c     Valencia
Name: Ciudades con dos equipos en primera, dtype: str
Id
a    Barcelona
d      Sevilla
Name: Ciudades con dos equipos en primera, dtype: str

In [112]:
# slicing
print(football_cities[:'c']) # incluye ambos extremos con el indice semantico
print(football_cities[:2])

Id
a    Barcelona
b       Madrid
c     Valencia
Name: Ciudades con dos equipos en primera, dtype: str
Id
a    Barcelona
b       Madrid
Name: Ciudades con dos equipos en primera, dtype: str

In [113]:
#cast a list
lista = list(football_cities[:'c'])
print(lista)
print(type(lista))

['Barcelona', 'Madrid', 'Valencia']
<class 'list'>

In [114]:
# El resultado es un objeto tipo Series (subconjunto)
# Pandas incluye el límite final ('c') cuando usamos etiquetas
print(type(football_cities[:'c']))

<class 'pandas.Series'>

In [115]:
# cast a ndarray
import numpy as np

# Convertir una Serie de Pandas a un arreglo puro de NumPy (ndarray)
cities = np.array(football_cities[:'c']) 

print(cities)
print(type(cities)) # Verificamos que el tipo ahora es <class 'numpy.ndarray'>

['Barcelona' 'Madrid' 'Valencia']
<class 'numpy.ndarray'>

In [116]:
# cast a dictionary
# Convertir una Serie de Pandas a un diccionario de Python
# Las etiquetas (índices) se convierten en las claves y los valores se mantienen

lista = dict(football_cities[:'c'])

print(lista)
print(type(lista)) # Verificamos que ahora es <class 'dict'>

{'a': 'Barcelona', 'b': 'Madrid', 'c': 'Valencia'}
<class 'dict'>

In [117]:
# uso de masks para seleccionar
fibonacci = pd.Series([0, 1, 1, 2, 3, 5, 8, 13, 21])
print(fibonacci)

# Crear una máscara para seleccionar valores mayores a 10
mask = fibonacci > 10
print(mask)

# Seleccionar los valores que cumplen la condición de la máscara
print(fibonacci[mask])

# Crear una Serie con los valores esperados
dst = pd.Series([13,21])
print(dst)

# Comparar si ambas Series son iguales
dst.equals(fibonacci)

# Guardar en una nueva Serie los valores filtrados con la máscara
fb = fibonacci[mask]

# Reiniciar los índices de la Serie filtrada
fb.reset_index(drop=True, inplace=True)

print(fb)

# Comprobar si la Serie filtrada coincide con la Serie esperada
dst.equals(fb)

0     0
1     1
2     1
3     2
4     3
5     5
6     8
7    13
8    21
dtype: int64
0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8     True
dtype: bool
7    13
8    21
dtype: int64
0    13
1    21
dtype: int64
0    13
1    21
dtype: int64

True

In [118]:
# aplicar funciones de numpy a la serie

import numpy as np

# Sumar todos los valores de la Serie usando la función sum de NumPy
print(np.sum(fibonacci))

54

In [119]:
# filtrado con np.where

distances = pd.Series([12.1, np.nan, 12.8, 76.9, 6.1, 7.2])

# Reemplazar los valores nulos por 2 y mantener los valores que no son nulos
valid_distances = np.where(pd.notnull(distances), distances, 2)

# Mostrar el resultado del filtrado
print(valid_distances)

# Verificar el tipo de dato del resultado
print(type(valid_distances))

[12.1  2.  12.8 76.9  6.1  7.2]
<class 'numpy.ndarray'>

### Iteración

In [120]:
# iterar sobre elementos
for value in fibonacci:
    # Mostrar cada valor de la Serie
    print('Value: ' + str(value))

# iterar sobre indices
for index in fibonacci.index:
    # Mostrar cada índice de la Serie
    print('Index: ' + str(index))

Value: 0
Value: 1
Value: 1
Value: 2
Value: 3
Value: 5
Value: 8
Value: 13
Value: 21
Index: 0
Index: 1
Index: 2
Index: 3
Index: 4
Index: 5
Index: 6
Index: 7
Index: 8

In [121]:
# iterar sobre elementos e índices al mismo tiempo

for index, value in fibonacci.items():
    # Mostrar el índice y el valor correspondiente de la Serie
    print('Index: ' + str(index) + ' Value: ' + str(value))

Index: 0 Value: 0
Index: 1 Value: 1
Index: 2 Value: 1
Index: 3 Value: 2
Index: 4 Value: 3
Index: 5 Value: 5
Index: 6 Value: 8
Index: 7 Value: 13
Index: 8 Value: 21

In [122]:
# iterar sobre elementos e índices usando zip

for index, value in zip(fibonacci.index, fibonacci):
    # Mostrar el índice y el valor correspondiente de la Serie
    print('Index: ' + str(index) + ' Value: ' + str(value))

Index: 0 Value: 0
Index: 1 Value: 1
Index: 2 Value: 1
Index: 3 Value: 2
Index: 4 Value: 3
Index: 5 Value: 5
Index: 6 Value: 8
Index: 7 Value: 13
Index: 8 Value: 21

## Series como diccionarios

* Interpretar el índice como clave
* Acepta operaciones para diccionarios

In [123]:
# crear una serie a partir de un diccionario

serie = pd.Series({'Carlos': 100, 'Marcos': 98})

# Mostrar los índices de la Serie
print(serie.index)

# Mostrar los valores de la Serie
print(serie.values)

# Mostrar la Serie completa
print(serie)

# Verificar el tipo de dato de la Serie
print(type(serie))

Index(['Carlos', 'Marcos'], dtype='str')
[100  98]
Carlos    100
Marcos     98
dtype: int64
<class 'pandas.Series'>

In [124]:
# añade y elimina elementos a través de índices
# Añadir un nuevo elemento a la Serie usando un índice
serie['Pedro'] = 12

# Modificar el valor de un elemento existente
serie['Pedro'] = 15

# Eliminar un elemento de la Serie mediante su índice
del serie['Marcos']

# Mostrar la Serie actualizada
print(serie)

Carlos    100
Pedro      15
dtype: int64

In [125]:
# query una serie
# Consultar un valor de la Serie mediante su índice
# print(serie['Marcos'])

# Verificar si el índice 'Marcos' existe dentro de la Serie
if 'Marcos' in serie:
    # Mostrar el valor asociado al índice 'Marcos'
    print(serie['Marcos'])

# Mostrar la Serie completa
print(serie)

Carlos    100
Pedro      15
dtype: int64

In [126]:
# suma de dos series

# suma de valores con el mismo índice (NaN si no aparece en ambas)

serie1 = pd.Series([10,20,30,40], index=range(4))
serie2 = pd.Series([1,2,3], index=range(3))

# Sumar las dos Series, los valores con índices iguales se suman
# y los índices que no existen en ambas generan NaN
suma = serie1 + serie2

# Mostrar el resultado de la suma
print(suma)

0    11.0
1    22.0
2    33.0
3     NaN
dtype: float64

In [127]:
# resta de series (similar a la suma)

# Restar los valores de las Series con el mismo índice
# Si un índice no existe en ambas Series, el resultado será NaN
print(serie1 - serie2)

0     9.0
1    18.0
2    27.0
3     NaN
dtype: float64

In [128]:
# operaciones de pre-filtrado

result = serie1 + serie2

# Reemplazar los valores nulos (NaN) por 0 usando una máscara con isnull()
result[pd.isnull(result)] = 0

# Mostrar la Serie después del reemplazo
print(result)

0    11.0
1    22.0
2    33.0
3     0.0
dtype: float64

### Diferencias entre Pandas Series y diccionario

* Diccionario, es una estructura que relaciona las claves y los valores de forma arbitraria.
* Series, estructura de forma estricta listas de valores con listas de índice asignado en la posición.
* Series, es más eficiente para ciertas operaciones que los dicionarios.
* En las Series los valores de entrada pueden ser listas o Numpy arrays.
* En Series los índices semánticos pueden ser integers o caracteres, en los valores igual.
* Series se podría entender entre una lista y un diccionario Python, pero es de una dimensión.

# DataFrame

* Datos tabulares (filas x columnas)
* Columnas: Series con índices compartidos

In [129]:
# crear un DataFrame a partir de un diccionario de elementos de la misma longitud

diccionario = {
    "Nombre": ["Marisa", "Laura", "Manuel"],
    "Edad": [34, 29, 12]
}

# Mostrar el diccionario creado
print(diccionario)

# Las claves del diccionario identifican las columnas del DataFrame
frame = pd.DataFrame(diccionario)

# Mostrar el DataFrame generado
display(frame)

{'Nombre': ['Marisa', 'Laura', 'Manuel'], 'Edad': [34, 29, 12]}

   Nombre  Edad
0  Marisa    34
1   Laura    29
2  Manuel    12

In [130]:
# crear un DataFrame a partir de un diccionario de elementos de la misma longitud

diccionario = {
    "Nombre": ["Marisa", "Laura", "Manuel"],
    "Edad": [34, 29, 12]
}

# las claves identifican columnas
# asignar índices personalizados a las filas del DataFrame
frame = pd.DataFrame(diccionario, index=['a', 'b', 'c'])

# Mostrar el DataFrame creado
display(frame)

   Nombre  Edad
a  Marisa    34
b   Laura    29
c  Manuel    12

In [131]:
# además de 'index', el parámetro 'columns' especifica el número y orden de las columnas

# Crear un DataFrame indicando las columnas que se desean mostrar y su orden
# Las columnas que no existen en el diccionario se crean con valores NaN
frame = pd.DataFrame(diccionario, columns=['Nacionalidad', 'Nombre', 'Edad', 'Profesion', 'Genero'])

# Mostrar el DataFrame creado
display(frame)

  Nacionalidad  Nombre  Edad Profesion Genero
0          NaN  Marisa    34       NaN    NaN
1          NaN   Laura    29       NaN    NaN
2          NaN  Manuel    12       NaN    NaN

In [132]:
# acceso a columnas

# Acceder a la columna "Nombre" del DataFrame
nombres = frame['Nombre']

# Mostrar la columna seleccionada
display(nombres)

# Verificar el tipo de dato obtenido
print(type(nombres))

# Acceder a la columna "Edad" del DataFrame
edades = frame['Edad']

# Mostrar la columna seleccionada
display(edades)

# Verificar el tipo de dato obtenido
print(type(edades))

0    Marisa
1     Laura
2    Manuel
Name: Nombre, dtype: str

<class 'pandas.Series'>

0    34
1    29
2    12
Name: Edad, dtype: int64

<class 'pandas.Series'>

In [133]:
# siempre que el nombre de la columna lo permita (espacios, ...)

# Acceder a una columna del DataFrame usando la notación de punto
nombres = frame.Profesion

# Mostrar la columna seleccionada
display(nombres)

# Verificar el tipo de dato obtenido
type(nombres)

0    NaN
1    NaN
2    NaN
Name: Profesion, dtype: object

pandas.Series

In [134]:
# acceso al primer nombre del DataFrame frame??
print(frame['Nombre'][0])
print(frame.Nombre[0])
print(nombres[0])

Marisa
Marisa
nan

### Formas de crear un DataFrame

* Con una Serie de pandas
* Lista de diccionarios
* Dicionario de Series de Pandas
* Con un array de Numpy de dos dimensiones
* Con array estructurado de Numpy

## Modificar DataFrames

In [135]:
# añadir columnas

diccionario = {
    "Nombre": ["Marisa", "Laura", "Manuel"],
    "Edad": [34, 29, 12]
}

# Crear un DataFrame con columnas adicionales aunque no existan en el diccionario
frame = pd.DataFrame(diccionario, columns=['Nacionalidad', 'Nombre', 'Edad', 'Profesion', 'Direccion'])

# Añadir valores a la columna "Direccion" para todas las filas
frame['Direccion'] = 'Desconocida'

# Mostrar el DataFrame actualizado
display(frame)

  Nacionalidad  Nombre  Edad Profesion    Direccion
0          NaN  Marisa    34       NaN  Desconocida
1          NaN   Laura    29       NaN  Desconocida
2          NaN  Manuel    12       NaN  Desconocida

In [136]:
# crear una lista con direcciones

lista_direcciones = ['Rue 13 del Percebe, 13', 'Evergreen Terrace, 3', 'Av de los Rombos, 12']

In [137]:
# añadir una lista de valores a la columna "Direccion"

# Asignar las direcciones de la lista a la columna del DataFrame
frame['Direccion'] = lista_direcciones

# Mostrar el DataFrame actualizado
display(frame)

  Nacionalidad  Nombre  Edad Profesion               Direccion
0          NaN  Marisa    34       NaN  Rue 13 del Percebe, 13
1          NaN   Laura    29       NaN    Evergreen Terrace, 3
2          NaN  Manuel    12       NaN    Av de los Rombos, 12

In [138]:
# añadir fila (requiere todos los valores)

# Crear una lista con los valores de la nueva fila
user_2 = ['Alemania', 'Klaus', 20, 'none', 'Desconocida']

# Añadir una nueva fila al DataFrame usando el índice 3
# La lista debe contener un valor para cada columna
frame.loc[3] = user_2

# Mostrar el DataFrame actualizado
display(frame)

  Nacionalidad  Nombre  Edad Profesion               Direccion
0          NaN  Marisa    34       NaN  Rue 13 del Percebe, 13
1          NaN   Laura    29       NaN    Evergreen Terrace, 3
2          NaN  Manuel    12       NaN    Av de los Rombos, 12
3     Alemania   Klaus    20      none             Desconocida

In [139]:
# eliminar fila (similar a Series)

frame = pd.DataFrame(diccionario, columns=['Nacionalidad', 'Nombre', 'Edad', 'Profesion'])

# Eliminar la fila con índice 2
# Necesitamos reasignar el frame porque drop() devuelve un nuevo DataFrame
# y no modifica el original a menos que usemos inplace=True
frame = frame.drop(2)

# Mostrar el DataFrame después de eliminar la fila
display(frame)

# Eliminar la columna "Nombre" usando axis=1 (indica que es una columna)
# inplace=True modifica directamente el DataFrame original
frame.drop('Nombre', axis=1, inplace=True)

# Mostrar el DataFrame actualizado
display(frame)

  Nacionalidad  Nombre  Edad Profesion
0          NaN  Marisa    34       NaN
1          NaN   Laura    29       NaN

  Nacionalidad  Edad Profesion
0          NaN    34       NaN
1          NaN    29       NaN

In [140]:
# eliminar columna

# Eliminar la columna "Profesion" del DataFrame usando del
del frame['Profesion']

# Mostrar el DataFrame actualizado
display(frame)

  Nacionalidad  Edad
0          NaN    34
1          NaN    29

In [141]:
# acceder a la traspuesta (como una matriz)
display(frame.T)

                0    1
Nacionalidad  NaN  NaN
Edad           34   29

In [142]:
# iteración sobre el DataFrame?

frame = pd.DataFrame(diccionario, columns=['Nacionalidad', 'Nombre', 'Edad', 'Profesion'])

# Mostrar el DataFrame creado
display(frame)

# Iterar sobre un DataFrame recorre los nombres de las columnas
for a in frame:
    # 'a' representa el nombre de cada columna del DataFrame
    print(a)

    # Mostrar el tipo de dato de 'a' (es un string)
    print(type(a))

  Nacionalidad  Nombre  Edad Profesion
0          NaN  Marisa    34       NaN
1          NaN   Laura    29       NaN
2          NaN  Manuel    12       NaN

Nacionalidad
<class 'str'>
Nombre
<class 'str'>
Edad
<class 'str'>
Profesion
<class 'str'>

In [143]:
# iteracion sobre filas

# Recorrer los valores de cada fila del DataFrame
for value in frame.values:
    # Mostrar los datos de la fila actual
    print(value)

    # Mostrar el tipo de dato de la fila (array de NumPy)
    print(type(value))

[nan 'Marisa' 34 nan]
<class 'numpy.ndarray'>
[nan 'Laura' 29 nan]
<class 'numpy.ndarray'>
[nan 'Manuel' 12 nan]
<class 'numpy.ndarray'>

In [144]:
# iterar sobre filas y luego sobre cada valor

# Recorrer cada fila del DataFrame
for values in frame.values:
    # Recorrer cada valor dentro de la fila actual
    for value in values:
        # Mostrar cada elemento de la fila
        print(value)

nan
Marisa
34
nan
nan
Laura
29
nan
nan
Manuel
12
nan

## Indexación y slicing con DataFrames

In [145]:
# crear una lista de diccionarios para generar un DataFrame

d1 = {'ciudad': 'Valencia', 'temperatura': 10, 'o2': 1}
d2 = {'ciudad': 'Barcelona', 'temperatura': 8}
d3 = {'ciudad': 'Valencia', 'temperatura': 9}
d4 = {'ciudad': 'Madrid', 'temperatura': 10, 'humedad': 80}
d5 = {'ciudad': 'Sevilla', 'temperatura': 15, 'humedad': 50, 'co2': 6}
d6 = {'ciudad': 'Valencia', 'temperatura': 10, 'humedad': 90, 'co2': 10}

# Crear una lista con los diccionarios
ls_data = [d1, d2, d3, d4, d5, d6]

# Crear un DataFrame usando los diccionarios como filas
# Los índices de las filas serán las letras a, b, c, d, e, f
df_data = pd.DataFrame(ls_data, index=list('abcdef'))

# Mostrar el DataFrame creado
display(df_data)

      ciudad  temperatura   o2  humedad   co2
a   Valencia           10  1.0      NaN   NaN
b  Barcelona            8  NaN      NaN   NaN
c   Valencia            9  NaN      NaN   NaN
d     Madrid           10  NaN     80.0   NaN
e    Sevilla           15  NaN     50.0   6.0
f   Valencia           10  NaN     90.0  10.0

In [146]:
# Acceso a un valor concreto por índice posicional [fila, columna]
# iloc usa posiciones numéricas empezando desde 0
print(df_data.iloc[1,1])

# Acceso a todos los valores hasta un índice por enteros
# Selecciona las primeras 3 filas y las primeras 4 columnas
display(df_data.iloc[:3, :4])

# Acceso a datos de manera explícita usando índices semánticos (nombres)
# loc permite acceder usando etiquetas de filas y columnas

# Obtener el valor de la fila 'a' y columna 'temperatura'
display(df_data.loc['a', 'temperatura'])

# Obtener desde la fila 'a' hasta 'c' y columnas desde el inicio hasta 'o2'
# En loc los límites sí se incluyen
display(df_data.loc[:'c', :'o2'])

# Obtener desde la fila 'a' hasta 'c' y columnas entre 'temperatura' y 'o2'
display(df_data.loc[:'c', 'temperatura':'o2'])

# Obtener todas las filas y únicamente las columnas seleccionadas
display(df_data.loc[:, ['ciudad', 'o2']])

8

      ciudad  temperatura   o2  humedad
a   Valencia           10  1.0      NaN
b  Barcelona            8  NaN      NaN
c   Valencia            9  NaN      NaN

np.int64(10)

      ciudad  temperatura   o2
a   Valencia           10  1.0
b  Barcelona            8  NaN
c   Valencia            9  NaN

   temperatura   o2
a           10  1.0
b            8  NaN
c            9  NaN

      ciudad   o2
a   Valencia  1.0
b  Barcelona  NaN
c   Valencia  NaN
d     Madrid  NaN
e    Sevilla  NaN
f   Valencia  NaN

In [147]:
# indexación con nombre de columna (por columnas)
# Acceder a una sola columna del DataFrame, devuelve una Serie
print(df_data['ciudad'])

# Acceder a varias columnas del DataFrame, devuelve un DataFrame
display(df_data[['ciudad', 'o2']])

a     Valencia
b    Barcelona
c     Valencia
d       Madrid
e      Sevilla
f     Valencia
Name: ciudad, dtype: str

      ciudad   o2
a   Valencia  1.0
b  Barcelona  NaN
c   Valencia  NaN
d     Madrid  NaN
e    Sevilla  NaN
f   Valencia  NaN

In [148]:
# Indexación con índice posicional (NO permitido para DataFrame)
# Al usar un número entre corchetes, Pandas lo interpreta como nombre de columna
# y no como posición de fila.
# Si no existe una columna llamada 0, generará un KeyError.
df_data[0]

KeyError: 0

In [149]:
# indexar por posición con 'iloc'
# Acceder a la primera fila del DataFrame usando su posición
# Devuelve una Serie donde los índices son los nombres de las columnas
print(df_data.iloc[0])

ciudad         Valencia
temperatura          10
o2                  1.0
humedad             NaN
co2                 NaN
Name: a, dtype: object

In [150]:
# indexar semántico con 'loc'
# Acceder a una fila usando su índice o etiqueta
# Devuelve una Serie donde los índices son los nombres de las columnas
df_data.loc['a']

ciudad         Valencia
temperatura          10
o2                  1.0
humedad             NaN
co2                 NaN
Name: a, dtype: object

In [151]:
# indexar semántico con 'loc'
# Acceder a las filas desde el índice inicial hasta el índice 'b'
# loc incluye el límite final, por eso devuelve las filas con índices 'a' y 'b'
# El resultado es un DataFrame
df_data.loc[:'b']

      ciudad  temperatura   o2  humedad  co2
a   Valencia           10  1.0      NaN  NaN
b  Barcelona            8  NaN      NaN  NaN

In [152]:
# slicing anidado
# Primero selecciona las filas desde el inicio hasta el índice 'b'
# Luego selecciona únicamente las columnas "o2" y "humedad"
df_data.loc[:'b'].loc[:, ["o2", "humedad"]]

    o2  humedad
a  1.0      NaN
b  NaN      NaN

In [153]:
# si se modifica una porción del DataFrame se modifica el DataFrame original
# (referencia)

# Mostrar el DataFrame original
display(df_data)

# Obtener una fila del DataFrame como una Serie
serie = df_data.loc['a']
print(serie)

# Modificar un valor de la Serie obtenida
# Puede modificar el DataFrame original porque trabaja con una referencia
# Puede generar un warning de copia (SettingWithCopyWarning)
serie.iloc[2] = 3000

# Mostrar el DataFrame después de la modificación
display(df_data)

# copiar DataFrame

# Crear una copia independiente de la fila seleccionada
df_2 = df_data.loc['a'].copy()

# Modificar la copia sin afectar el DataFrame original
df_2.iloc[2] = 3000

# Mostrar la copia modificada
display(df_2)

# Mostrar el DataFrame original para comprobar que no cambió
display(df_data)

      ciudad  temperatura   o2  humedad   co2
a   Valencia           10  1.0      NaN   NaN
b  Barcelona            8  NaN      NaN   NaN
c   Valencia            9  NaN      NaN   NaN
d     Madrid           10  NaN     80.0   NaN
e    Sevilla           15  NaN     50.0   6.0
f   Valencia           10  NaN     90.0  10.0

ciudad         Valencia
temperatura          10
o2                  1.0
humedad             NaN
co2                 NaN
Name: a, dtype: object

      ciudad  temperatura   o2  humedad   co2
a   Valencia           10  1.0      NaN   NaN
b  Barcelona            8  NaN      NaN   NaN
c   Valencia            9  NaN      NaN   NaN
d     Madrid           10  NaN     80.0   NaN
e    Sevilla           15  NaN     50.0   6.0
f   Valencia           10  NaN     90.0  10.0

ciudad         Valencia
temperatura          10
o2                 3000
humedad             NaN
co2                 NaN
Name: a, dtype: object

      ciudad  temperatura   o2  humedad   co2
a   Valencia           10  1.0      NaN   NaN
b  Barcelona            8  NaN      NaN   NaN
c   Valencia            9  NaN      NaN   NaN
d     Madrid           10  NaN     80.0   NaN
e    Sevilla           15  NaN     50.0   6.0
f   Valencia           10  NaN     90.0  10.0

In [154]:
# ambos aceptan 'axis' como argumento

# iloc con axis=1 permite acceder a columnas mediante su posición
# df_data.iloc(axis=1)[0] --> todos los valores asignados a la primera columna "ciudad"

# loc con axis=1 permite acceder a columnas mediante su nombre
# Equivale a usar df_data['ciudad']
df_data.loc(axis=1)['ciudad']

a     Valencia
b    Barcelona
c     Valencia
d       Madrid
e      Sevilla
f     Valencia
Name: ciudad, dtype: str

In [155]:
# qué problema puede tener este fragmento?

frame = pd.DataFrame(
    {"Name": ['Carlos', 'Pedro'], "Age": [34, 22]},
    index=[1, 0]
)

# El problema es que los índices están desordenados.
# Esto puede causar confusión al acceder a los datos porque las filas
# no siguen el orden habitual de creación.
display(frame)

     Name  Age
1  Carlos   34
0   Pedro   22

In [156]:
# por defecto, pandas interpreta índice posicional --> error en frames
# cuando hay posible ambigüedad, utilizar loc y iloc

# Acceder a la primera fila por posición (posición 0)
# iloc trabaja con índices numéricos de posición
print('Primera fila\n')
print(frame.iloc[0])

# Acceder a la fila cuyo índice es 0
# loc trabaja con las etiquetas o índices definidos en el DataFrame
print('\nElemento con index 0\n')
print(frame.loc[0])

Primera fila

Name    Carlos
Age         34
Name: 1, dtype: object

Elemento con index 0

Name    Pedro
Age        22
Name: 0, dtype: object

## Objeto Index de Pandas

In [157]:
# Construcción de índices

# Crear un objeto Index de Pandas con una lista de valores
ind = pd.Index([2, 3, 5, 23, 26])

# Recuperar un valor del índice mediante su posición
print(ind[3])

# Recuperar valores del índice usando slicing
print(ind[::2])

23
Index([2, 5, 26], dtype='int64')

In [158]:
# usar un objeto index al crear dataframe

# Crear un DataFrame utilizando un objeto Index como índices de las filas
frame = pd.DataFrame(
    {
        "Name": ['Carlos', 'Pedro', 'Manolo', 'Luis', 'Alberto'],
        "Age": [34, 22, 15, 55, 23]
    },
    index=ind
)

# Mostrar el DataFrame creado
display(frame)

       Name  Age
2    Carlos   34
3     Pedro   22
5    Manolo   15
23     Luis   55
26  Alberto   23

In [159]:
# Son inmutables! No se modifican los datos.
ind[3] = 8

TypeError: Index does not support mutable operations

In [160]:
# change index column

# Crear un DataFrame usando el objeto Index como índice inicial
frame = pd.DataFrame(
    {
        "Name": ['Carlos', 'Pedro', 'Manolo', 'Luis', 'Alberto'],
        "Age": [34, 22, 15, 55, 23]
    },
    index=ind
)

# Mostrar el DataFrame inicial
display(frame)

# Cambiar la columna "Age" para que sea el nuevo índice del DataFrame
# inplace=True aplica el cambio directamente sobre el DataFrame
frame.set_index('Age', inplace=True)

# Mostrar el DataFrame con el nuevo índice
display(frame)

       Name  Age
2    Carlos   34
3     Pedro   22
5    Manolo   15
23     Luis   55
26  Alberto   23

        Name
Age
34    Carlos
22     Pedro
15    Manolo
55      Luis
23   Alberto

## Slicing

In [161]:
# slice por filas

# Crear un diccionario con información de personajes
d_and_d_characters = {
    'Name': ['bundenth', 'theorin', 'barlok'],
    'Strength': [10, 12, 19],
    'Wisdom': [20, 13, 6]
}

# Crear un DataFrame con índices personalizados
character_data = pd.DataFrame(d_and_d_characters, index=['a', 'b', 'c'])

# Mostrar el DataFrame creado
display(character_data)

# Seleccionar todas las filas excepto la última
display(character_data[:-1])

# Seleccionar la fila con posición 1
# El límite final no se incluye en el slicing
display(character_data[1:2])

       Name  Strength  Wisdom
a  bundenth        10      20
b   theorin        12      13
c    barlok        19       6

       Name  Strength  Wisdom
a  bundenth        10      20
b   theorin        12      13

      Name  Strength  Wisdom
b  theorin        12      13

In [162]:
# slicing para columnas
# Seleccionar únicamente las columnas "Name" y "Wisdom" del DataFrame
display(character_data[['Name', 'Wisdom']])

       Name  Wisdom
a  bundenth      20
b   theorin      13
c    barlok       6

In [163]:
# slicing con 'loc' e 'iloc'
# Seleccionar filas desde la posición 1 hasta el final usando iloc
# iloc trabaja con posiciones numéricas
display(character_data.iloc[1:])

# Seleccionar filas desde el inicio hasta el índice 'b'
# y columnas desde 'Name' hasta 'Strength' usando loc
# loc trabaja con etiquetas e incluye el límite final
display(character_data.loc[:'b', 'Name':'Strength'])

      Name  Strength  Wisdom
b  theorin        12      13
c   barlok        19       6

       Name  Strength
a  bundenth        10
b   theorin        12

¿Cómo filtrar filas y columnas? Por ejemplo, para todos los personajes, obtener ‘Name’ y ‘Strength’

In [164]:
# usando 'loc' para hacer slicing
display(character_data.loc[:,'Name':'Strength'])

       Name  Strength
a  bundenth        10
b   theorin        12
c    barlok        19

In [165]:
# usando 'loc' para buscar específicamente filas y columnas
display(character_data.loc[ ['a','c'], ['Name','Wisdom'] ])

       Name  Wisdom
a  bundenth      20
c    barlok       6

In [166]:
# lo mismo con 'iloc'?

# Seleccionar filas y columnas específicas mediante sus posiciones
# iloc trabaja con índices numéricos de posición

# Seleccionar filas 0 y 2, y columnas 0 y 2
display(character_data.iloc[[0, 2], [0, 2]])

# Seleccionar la primera y última fila, y la primera y última columna
display(character_data.iloc[[0, -1], [0, -1]])

       Name  Wisdom
a  bundenth      20
c    barlok       6

       Name  Wisdom
a  bundenth      20
c    barlok       6

In [167]:
# lista de los personajes con el atributo Strength > 11
display(character_data.loc[character_data['Strength'] > 11, ['Name', 'Strength']])

      Name  Strength
b  theorin        12
c   barlok        19

In [168]:
# listar los personajes con Strength > 15 o Wisdom > 15
display(character_data.loc[(character_data['Strength'] > 15) | (character_data['Wisdom'] > 15)])

       Name  Strength  Wisdom
a  bundenth        10      20
c    barlok        19       6

# Cargar y guardar datos en pandas

In [169]:
# Guardar a csv
import os
ruta = os.path.join("res" ,"o_d_d_characters.csv")
#character_data.to_csv(ruta, sep=';') # sep por defecto: ','

In [170]:
# cargar un archivo CSV
# Leer un archivo CSV indicando que el separador de columnas es ';'
loaded = pd.read_csv(ruta, sep=';')

# Mostrar el DataFrame cargado
display(loaded)

  Unnamed: 0      Name  Strength  Wisdom
0          a  bundenth        10      20
1          b   theorin        12      13
2          c    barlok        19       6

In [171]:
# crear la ruta del archivo
# Unir las carpetas y el nombre del archivo para obtener la ruta completa
ruta = os.path.join("res", "titanic.csv")

In [172]:
# cargar el archivo titanic.csv
# Leer el archivo CSV usando coma como separador de columnas
titanic = pd.read_csv(ruta, sep=',')

# Mostrar el DataFrame cargado
display(titanic)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [173]:
# cargar un archivo CSV usando una columna como índice
# Leer el archivo CSV indicando que la primera columna será el índice del DataFrame
loaded = pd.read_csv(ruta, sep=',', index_col=0)

# Mostrar el DataFrame cargado
display(loaded)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

**otros argumentos to_csv()**

* na_rep=‘string’ –> representar valores NaN en el archivo csv

**otros argumentos read_csv()**

* na_values=‘string’

Pandas también ofrece funciones para leer/guardar a otros formatos estándares:JSON, HDF5 o Excel en su [API](https://pandas.pydata.org/pandas-docs/stable/reference/io.html)

# Ejemplo práctico en pandas

* [MovieLens dataset](https://grouplens.org/datasets/movielens/)
* Reviews de películas
* 1 millón de entradas
* Datos demográficos de usuarios

In [174]:
# importar librerías necesarias

import numpy as np
import pandas as pd
import zipfile  # para descomprimir archivos zip
import urllib.request  # para descargar archivos desde una URL
import os

# descargar el dataset MovieLens

# URL del archivo comprimido del dataset
url = 'http://files.grouplens.org/datasets/movielens/ml-1m.zip'

# Crear la ruta donde se guardará el archivo descargado
ruta = os.path.join("res", "ml-1m.zip")

# Descargar el archivo desde la URL y guardarlo en la ruta indicada
urllib.request.urlretrieve(url, ruta)

('res\\ml-1m.zip', <http.client.HTTPMessage at 0x28c6ba19590>)

In [175]:
# descomprimiendo archivo zip
# Definir la ruta donde se extraerán los archivos
ruta_ext = os.path.join("res")

# Abrir el archivo ZIP en modo lectura
with zipfile.ZipFile(ruta, 'r') as z:
    # Mostrar mensaje de inicio de extracción
    print('Extracting all files...')

    # Extraer todos los archivos en la ruta indicada
    z.extractall(ruta_ext)

    # Mostrar mensaje de finalización
    print('Done!')

# take a look at readme y revisar formatos
# Revisar el archivo readme para conocer la estructura y formatos de los datos

Extracting all files...
Done!

In [176]:
# Ruta del archivo de usuarios
ruta_users = os.path.join("res", "ml-1m", "users.dat")

# Carga los datos de usuarios en un DataFrame
users_dataset = pd.read_csv(ruta_users, sep='::', index_col=0, engine='python')

# Muestra los datos
display(users_dataset)

      F  1.1  10  48067
1
2     M   56  16  70072
3     M   25  15  55117
4     M   45   7  02460
5     M   25  20  55455
6     F   50   9  55117
...  ..  ...  ..    ...
6036  F   25  15  32603
6037  F   45   1  76006
6038  F   56   1  14706
6039  F   45   0  01060
6040  M   25   6  11106

[6039 rows x 4 columns]

In [177]:
# Varios problemas
# sin cabecera! primer valor se ha perdido
# las columnas no tienen nombres
pd.read_csv?

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols: 'UsecolsArgType' = None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters: 'Mapping[HashableT, Callable] | None' = None,
    true_values: 'list | None' = None,
    false_values: 'list | None' = None,
    skipinitialspace: 'bool' = False,
    skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None,
    keep_default_na: 'bool' = True,
    na_filter: 'bool' = True,
    skip_blank_lines: 'bool' = True,
    parse_dates: 'bool | Sequence[Hashable] | None' = None,
    date_format: 'str | dict[Hashable, str] | None' = None,
    dayfirst: 'bool' = False,
    cache_dates: 'bool' = True,
    iterator: 'bool' = False,
    chunksize: 'int | None' = None,
    compression: 'CompressionOptions' = 'infer',
    thousands: 'str | None' = None,
    decimal: 'str' = '.',
    lineterminator: 'str | None' = None,
    quotechar: 'str' = '"',
    quoting: 'int' = 0,
    doublequote: 'bool' = True,
    escapechar: 'str | None' = None,
    comment: 'str | None' = None,
    encoding: 'str | None' = None,
    encoding_errors: 'str | None' = 'strict',
    dialect: 'str | csv.Dialect | None' = None,
    on_bad_lines: 'str' = 'error',
    low_memory: 'bool' = True,
    memory_map: 'bool' = False,
    float_precision: "Literal['high', 'legacy', 'round_trip'] | None" = None,
    storage_options: 'StorageOptions | None' = None,
    dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>,
) -> 'DataFrame | TextFileReader'
Docstring:
Read a comma-separated values (csv) file into DataFrame.

Also supports optionally iterating or breaking of the file
into chunks.

Additional help can be found in the online docs for
`IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

Parameters
----------
filepath_or_buffer : str, path object or file-like object
    Any valid string path is acceptable. The string could be a URL. Valid
    URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
    expected. A local file could be: file://localhost/path/to/table.csv.

    If you want to pass in a path object, pandas accepts any ``os.PathLike``.

    By file-like object, we refer to objects with a ``read()`` method, such as
    a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
sep : str, default ','
    Character or regex pattern to treat as the delimiter. If ``sep=None``, the
    C engine cannot automatically detect
    the separator, but the Python parsing engine can, meaning the latter will
    be used and automatically detect the separator from only the first valid
    row of the file by Python's builtin sniffer tool, ``csv.Sniffer``.
    In addition, separators longer than 1 character and different from
    ``'\s+'`` will be interpreted as regular expressions and will also force
    the use of the Python parsing engine. Note that regex delimiters are prone
    to ignoring quoted data. Regex example: ``'\r\t'``.
delimiter : str, optional
    Alias for ``sep``.
header : int, Sequence of int, 'infer' or None, default 'infer'
    Row number(s) containing column labels and marking the start of the
    data (zero-indexed). Default behavior is to infer the column names:
    if no ``names``
    are passed the behavior is identical to ``header=0`` and column
    names are inferred from the first line of the file, if column
    names are passed explicitly to ``names`` then the behavior is identical to
    ``header=None``. Explicitly pass ``header=0`` to be able to
    replace existing names. The header can be a list of integers that
    specify row locations for a :class:`~pandas.MultiIndex` on the columns
    e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
    skipped (e.g. 2 in this example is skipped). Note that this
    parameter ignores commented lines and empty lines if
    ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
    data rather than the first line of the file.

    When inferred from the file contents, headers are kept distinct from
    each other by renaming duplicate names with a numeric suffix of the form
    ``".{count}"`` starting from 1, e.g. ``"foo"`` and ``"foo.1"``.
    Empty headers are named ``"Unnamed: {i}"`` or ``
    "Unnamed: {i}_level_{level}"``
    in the case of MultiIndex columns.
names : Sequence of Hashable, optional
    Sequence of column labels to apply. If the file contains a header row,
    then you should explicitly pass ``header=0`` to override the column names.
    Duplicates in this list are not allowed.
index_col : Hashable, Sequence of Hashable or False, optional
    Column(s) to use as row label(s), denoted either by column labels or column
    indices.  If a sequence of labels or indices is given,
    :class:`~pandas.MultiIndex`
    will be formed for the row labels.

    Note: ``index_col=False`` can be used to force pandas to *not* use the first
    column as the index, e.g., when you have a malformed file with delimiters at
    the end of each line.
usecols : Sequence of Hashable or Callable, optional
    Subset of columns to select, denoted either
    by column labels or column indices.
    If list-like, all elements must either
    be positional (i.e. integer indices into the document columns) or strings
    that correspond to column names provided either by the user in ``names`` or
    inferred from the document header row(s).
    If ``names`` are given, the document
    header row(s) are not taken into account. For example, a valid list-like
    ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
    Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
    To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
    preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
    for columns in ``['foo', 'bar']`` order or
    ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
    for ``['bar', 'foo']`` order.

    If callable, the callable function will be evaluated against the column
    names, returning names where the callable function evaluates to ``True``. An
    example of a valid callable argument would be ``lambda x: x.upper() in
    ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
    parsing time and lower memory usage.
dtype : dtype or dict of {Hashable : dtype}, optional
    Data type(s) to apply to either the whole dataset or individual columns.
    E.g., ``{'a': np.float64, 'b': np.int32, 'c': 'Int64'}``
    Use ``str`` or ``object`` together with suitable ``na_values`` settings
    to preserve and not interpret ``dtype``.
    If ``converters`` are specified, they will be applied INSTEAD
    of ``dtype`` conversion. Specify a ``defaultdict`` as input where
    the default determines the ``dtype``
    of the columns which are not explicitly
    listed.
engine : {'c', 'python', 'pyarrow'}, optional
    Parser engine to use. The C and pyarrow engines are faster,
    while the python engine
    is currently more feature-complete. Multithreading
    is currently only supported by
    the pyarrow engine. Some features of the "pyarrow" engine
    are unsupported or may not work correctly.
converters : dict of {Hashable : Callable}, optional
    Functions for converting values in specified columns. Keys can either
    be column labels or column indices.
true_values : list, optional
    Values to consider as ``True`` in addition
    to case-insensitive variants of 'True'.
false_values : list, optional
    Values to consider as ``False`` in addition to case-insensitive
    variants of 'False'.
skipinitialspace : bool, default False
    Skip spaces after delimiter.
skiprows : int, list of int or Callable, optional
    Line numbers to skip (0-indexed) or number of lines to skip (``int``)
    at the start of the file.

    If callable, the callable function will be evaluated against the row
    indices, returning ``True`` if the row should be skipped and ``False``
    otherwise.
    An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
skipfooter : int, default 0
    Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
nrows : int, optional
    Number of rows of file to read. Useful for reading pieces of large files.
    Refers to the number of data rows in the returned DataFrame, excluding:

    * The header row containing column names.
    * Rows before the header row, if ``header=1`` or larger.

    Example usage:

    * To read the first 999,999 (non-header) rows:
      ``read_csv(..., nrows=999999)``

    * To read rows 1,000,000 through 1,999,999:
      ``read_csv(..., skiprows=1000000, nrows=999999)``

na_values : Hashable, Iterable of Hashable or dict of {Hashable : Iterable},
    optional
    Additional strings to recognize as ``NA``/``NaN``. If ``dict``
    passed, specific
    per-column ``NA`` values.  By default the following values
    are interpreted as
    ``NaN``: empty string, "NaN", "N/A", "NULL", and other common
    representations of missing data.
keep_default_na : bool, default True
    Whether or not to include the default ``NaN`` values when parsing the data.
    Depending on whether ``na_values`` is passed in, the behavior is as follows:

    * If ``keep_default_na`` is ``True``, and ``na_values``
      are specified, ``na_values``
      is appended to the default ``NaN`` values used for parsing.
    * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
      the default ``NaN`` values are used for parsing.
    * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
      the ``NaN`` values specified ``na_values`` are used for parsing.
    * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
      strings will be parsed as ``NaN``.

    Note that if ``na_filter`` is passed in as ``False``,
    the ``keep_default_na`` and
    ``na_values`` parameters will be ignored.
na_filter : bool, default True
    Detect missing value markers (empty strings and the value of ``na_values``). In
    data without any ``NA`` values, passing ``na_filter=False`` can improve the
    performance of reading a large file.
skip_blank_lines : bool, default True
    If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
parse_dates : bool, None, list of Hashable, default None
    The behavior is as follows:

    * ``bool``. If ``True`` -> try parsing the index.
    * ``None``. Behaves like ``True`` if ``date_format`` is specified.
    * ``list`` of ``int`` or names.
      e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
      each as a separate date column.

    If a column or index cannot be represented as an array of ``datetime``,
    say because of an unparsable value or a mixture of timezones, the column
    or index will be returned unaltered as an ``object`` data type. For
    non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
    :func:`~pandas.read_csv`.

    Note: A fast-path exists for iso8601-formatted dates.
date_format : str or dict of column -> format, optional
    Format to use for parsing dates and/or times when
    used in conjunction with ``parse_dates``.
    The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
    `strftime documentation
    <https://docs.python.org/3/library/datetime.html
    #strftime-and-strptime-behavior>`_ for more information on choices, though
    note that :const:`"%f"`` will parse all the way up to nanoseconds.
    You can also pass:

    - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
      time string (not necessarily in exactly the same format);
    - "mixed", to infer the format for each element individually. This is risky,
      and you should probably use it along with `dayfirst`.

    .. versionadded:: 2.0.0
dayfirst : bool, default False
    DD/MM format dates, international and European format.
cache_dates : bool, default True
    If ``True``, use a cache of unique, converted dates to apply the ``datetime``
    conversion. May produce significant speed-up when parsing duplicate
    date strings, especially ones with timezone offsets.

iterator : bool, default False
    Return ``TextFileReader`` object for iteration or getting chunks with
    ``get_chunk()``.
chunksize : int, optional
    Number of lines to read from the file per chunk. Passing a value will cause the
    function to return a ``TextFileReader`` object for iteration.
    See the `IO Tools docs
    <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
    for more information on ``iterator`` and ``chunksize``.

compression : str or dict, default 'infer'
    For on-the-fly decompression of on-disk data.
    If 'infer' and 'filepath_or_buffer' is
    path-like, then detect compression from the following extensions: '.gz',
    '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
    (otherwise no compression).
    If using 'zip' or 'tar', the ZIP file must contain only
    one data file to be read in.
    Set to ``None`` for no decompression.
    Can also be a dict with key ``'method'`` set
    to one of {``'zip'``, ``'gzip'``, ``'bz2'``,
    ``'zstd'``, ``'xz'``, ``'tar'``} and
    other key-value pairs are forwarded to
    ``zipfile.ZipFile``, ``gzip.GzipFile``,
    ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
    ``tarfile.TarFile``, respectively.
    As an example, the following could be passed for
    Zstandard decompression using a
    custom compression dictionary:
    ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

thousands : str (length 1), optional
    Character acting as the thousands separator in numerical values.
decimal : str (length 1), default '.'
    Character to recognize as decimal point (e.g., use ',' for European data).
lineterminator : str (length 1), optional
    Character used to denote a line break. Only valid with C parser.
quotechar : str (length 1), optional
    Character used to denote the start and end of a quoted item. Quoted
    items can include the ``delimiter`` and it will be ignored.
quoting : {0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL,
    2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}, default csv.QUOTE_MINIMAL
    Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
    ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that
    only fields containing special
    characters are quoted (e.g., characters defined
    in ``quotechar``, ``delimiter``,
    or ``lineterminator``.
doublequote : bool, default True
    When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
    whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
    field as a single ``quotechar`` element.
escapechar : str (length 1), optional
    Character used to escape other characters.
comment : str (length 1), optional
    Character indicating that the remainder of line should not be parsed.
    If found at the beginning
    of a line, the line will be ignored altogether. This parameter must be a
    single character. Like empty lines (as long as ``skip_blank_lines=True``),
    fully commented lines are ignored by the parameter ``header`` but not by
    ``skiprows``. For example, if ``comment='#'``, parsing
    ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
    treated as the header.
encoding : str, optional, default 'utf-8'
    Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
    standard encodings
    <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

encoding_errors : str, optional, default 'strict'
    How encoding errors are treated. `List of possible values
    <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

dialect : str or csv.Dialect, optional
    If provided, this parameter will override values (default or not) for the
    following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
    ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
    override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
    documentation for more details.
on_bad_lines : {'error', 'warn', 'skip'} or Callable, default 'error'
    Specifies what to do upon encountering a bad line (a line with too many fields).
    Allowed values are:

    - ``'error'``, raise an Exception when a bad line is encountered.
    - ``'warn'``, raise a warning when a bad line is
      encountered and skip that line.
    - ``'skip'``, skip bad lines without raising or warning when
      they are encountered.
    - Callable, function that will process a single bad line.
        - With ``engine='python'``, function with signature
          ``(bad_line: list[str]) -> list[str] | None``.
          ``bad_line`` is a list of strings split by the ``sep``.
          If the function returns ``None``, the bad line will be ignored.
          If the function returns a new ``list`` of strings with
          more elements than
          expected, a ``ParserWarning`` will be emitted while
          dropping extra elements.
        - With ``engine='pyarrow'``, function with signature
          as described in pyarrow documentation: `invalid_row_handler
          <https://arrow.apache.org/docs/python
          /generated/pyarrow.csv.ParseOptions.html
          #pyarrow.csv.ParseOptions.invalid_row_handler>`_.

    .. versionchanged:: 2.2.0

        Callable for ``engine='pyarrow'``

low_memory : bool, default True
    Internally process the file in chunks, resulting in lower memory use
    while parsing, but possibly mixed type inference.  To ensure no mixed
    types either set ``False``, or specify the type with the ``dtype`` parameter.
    Note that the entire file is read into a single :class:`~pandas.DataFrame`
    regardless, use the ``chunksize`` or ``iterator``
    parameter to return the data in
    chunks. (Only valid with C parser).
memory_map : bool, default False
    If a filepath is provided for ``filepath_or_buffer``, map the file object
    directly onto memory and access the data directly from there. Using this
    option can improve performance because there is no longer any I/O overhead.
float_precision : {'high', 'legacy', 'round_trip'}, optional
    Specifies which converter the C engine should use for floating-point
    values. The options are ``None`` or ``'high'`` for the ordinary converter,
    ``'legacy'`` for the original lower precision pandas converter, and
    ``'round_trip'`` for the round-trip converter.

storage_options : dict, optional
    Extra options that make sense for a particular storage connection, e.g.
    host, port, username, password, etc. For HTTP(S) URLs the key-value pairs
    are forwarded to ``urllib.request.Request`` as header options. For other
    URLs (e.g. starting with "s3://", and "gcs://") the key-value pairs are
    forwarded to ``fsspec.open``. Please see ``fsspec`` and ``urllib`` for more
    details, and for more examples on storage options refer `here
    <https://pandas.pydata.org/docs/user_guide/io.html?
    highlight=storage_options#reading-writing-remote-files>`_.

dtype_backend : {'numpy_nullable', 'pyarrow'}
    Back-end data type applied to the resultant :class:`DataFrame`
    (still experimental). If not specified, the default behavior

In [178]:
# especificar nombres, cargar sin cabecera
users_dataset = pd.read_csv(ruta_users, sep='::', index_col=0,
header=None, names=['UserID','Gender','Age','Occupation','Zip-code'],
engine='python')

# Mostrar los datos cargados
display(users_dataset)

       Gender  Age  Occupation Zip-code
UserID
1           F    1          10    48067
2           M   56          16    70072
3           M   25          15    55117
4           M   45           7    02460
5           M   25          20    55455
...       ...  ...         ...      ...
6036        F   25          15    32603
6037        F   45           1    76006
6038        F   56           1    14706
6039        F   45           0    01060
6040        M   25           6    11106

[6040 rows x 4 columns]

In [179]:
# samplear la tabla
# mostrar una muestra aleatoria de la tabla
display(users_dataset.sample(10))

       Gender  Age  Occupation Zip-code
UserID
5080        F   50          12    95472
1337        M   56          17    97146
3908        M   25           0    10021
1690        M   35          16    98029
5377        F   18           3    10017
5973        M    1          10    54701
1333        M   25          17    06460
2176        M    1          19    73505
4054        M   35           3    68122
3749        F   25           0    60664

In [180]:
#samplear la cabeza
# mostrar las primeras filas de la tabla
display(users_dataset.head(4))

       Gender  Age  Occupation Zip-code
UserID
1           F    1          10    48067
2           M   56          16    70072
3           M   25          15    55117
4           M   45           7    02460

In [181]:
# samplear la cola
# mostrar las últimas filas de la tabla
display(users_dataset.tail(10))

       Gender  Age  Occupation Zip-code
UserID
6031        F   18           0    45123
6032        M   45           7    55108
6033        M   50          13    78232
6034        M   25          14    94117
6035        F   25           1    78734
6036        F   25          15    32603
6037        F   45           1    76006
6038        F   56           1    14706
6039        F   45           0    01060
6040        M   25           6    11106

In [182]:
# tipos de datos sobre las columnas
users_dataset.dtypes

Gender          str
Age           int64
Occupation    int64
Zip-code        str
dtype: object

In [183]:
# filtrar registros donde el código postal tiene más de 5 caracteres
display(users_dataset[users_dataset['Zip-code'].str.len() > 5])

       Gender  Age  Occupation    Zip-code
UserID
161         M   45          16  98107-2117
233         F   45          20  37919-4204
293         M   56           1  55337-4056
458         M   50          16  55405-2546
506         M   25          16  55103-1006
...       ...  ...         ...         ...
5682        M   18           0  23455-4959
5904        F   45          12      954025
5925        F   25           0  90035-4444
5967        M   50          16  73069-5429
5985        F   18           4  78705-5221

[81 rows x 4 columns]

In [184]:
# información general sobre atributos numéricos
display(users_dataset.describe())

               Age   Occupation
count  6040.000000  6040.000000
mean     30.639238     8.146854
std      12.895962     6.329511
min       1.000000     0.000000
25%      25.000000     3.000000
50%      25.000000     7.000000
75%      35.000000    14.000000
max      56.000000    20.000000

In [185]:
# mostrar información general de la tabla
users_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 6040 entries, 1 to 6040
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Gender      6040 non-null   str
 1   Age         6040 non-null   int64
 2   Occupation  6040 non-null   int64
 3   Zip-code    6040 non-null   str
dtypes: int64(2), str(2)
memory usage: 224.6 KB

In [186]:
# incluir otros atributos (no todo tiene sentido)
display(users_dataset.describe(include='all'))

       Gender          Age   Occupation Zip-code
count    6040  6040.000000  6040.000000     6040
unique      2          NaN          NaN     3439
top         M          NaN          NaN    48104
freq     4331          NaN          NaN       19
mean      NaN    30.639238     8.146854      NaN
std       NaN    12.895962     6.329511      NaN
min       NaN     1.000000     0.000000      NaN
25%       NaN    25.000000     3.000000      NaN
50%       NaN    25.000000     7.000000      NaN
75%       NaN    35.000000    14.000000      NaN
max       NaN    56.000000    20.000000      NaN

In [187]:
# cuántos usuarios son mujeres (Gender='F')
len(users_dataset[users_dataset['Gender'] == 'F'])

# select count(*) from users_dataset where users_dataset.Gender = 'F'

1709

In [188]:
# mostrar solo los menores de edad
under_age = users_dataset[users_dataset['Age'] == 1]
print(len(under_age))
display(under_age.sample(10))

222

       Gender  Age  Occupation Zip-code
UserID
5228        M    1           0    75070
719         M    1           0    75070
5255        M    1          10    55305
210         F    1          10    25801
1982        M    1          10    80540
86          F    1          10    54467
1280        M    1          10    97801
888         F    1          10    08820
2199        M    1          10    60613
1220        M    1          10    48073

In [189]:
# filtrar edad incorrecta (mínimo 18) SettingWithCopyWarning!!!
users_dataset = pd.read_csv(ruta_users, sep='::', index_col=0,
header=None, names=['UserID','Gender','Age','Occupation','Zip-code'],
engine='python')

under_age = users_dataset[users_dataset['Age'] == 1]
under_age.loc['Age'] = np.nan

# mostrar los primeros registros filtrados
display(under_age.head())

# users_dataset[users_dataset['Age'] < 18] = under_age
# display(users_dataset)

       Gender  Age  Occupation Zip-code
UserID
1           F  1.0        10.0    48067
19          M  1.0        10.0    48073
51          F  1.0        10.0    10562
75          F  1.0        10.0    01748
86          F  1.0        10.0    54467

In [190]:
# filtrar edad incorrecta (mínimo 18) Fixing it by Copying the slice
users_dataset = pd.read_csv(ruta_users, sep='::', index_col=0,
header=None, names=['UserID','Gender','Age','Occupation','Zip-code'],
engine='python')

under_age = users_dataset[users_dataset['Age'] == 1]

# crear una copia de los datos filtrados
under_age_copy = under_age.copy()

display(under_age_copy.head())

# reemplazar la edad incorrecta por valores nulos
under_age_copy['Age'] = np.nan

display(under_age_copy.head())

# actualizar los registros en la tabla original
users_dataset[users_dataset['Age'] == 1] = under_age_copy

display(users_dataset.head())

       Gender  Age  Occupation Zip-code
UserID
1           F    1          10    48067
19          M    1          10    48073
51          F    1          10    10562
75          F    1          10    01748
86          F    1          10    54467

       Gender  Age  Occupation Zip-code
UserID
1           F  NaN          10    48067
19          M  NaN          10    48073
51          F  NaN          10    10562
75          F  NaN          10    01748
86          F  NaN          10    54467

       Gender   Age  Occupation Zip-code
UserID
1           F   NaN          10    48067
2           M  56.0          16    70072
3           M  25.0          15    55117
4           M  45.0           7    02460
5           M  25.0          20    55455

In [191]:
# filtrar edad incorrecta (mínimo 18) Remove them from the dataset
users_dataset = pd.read_csv(ruta_users, sep='::', index_col=0,
header=None, names=['UserID','Gender','Age','Occupation','Zip-code'],
engine='python')

display(users_dataset[users_dataset['Age'] == 1].head(4))

# reemplazar edades incorrectas por valores nulos
users_dataset.loc[users_dataset['Age'] == 1, 'Age'] = np.nan

display(users_dataset)
display(users_dataset.loc[pd.isnull(users_dataset['Age'])].head(4))

# eliminar registros con valores nulos en la edad
users_dataset.drop(users_dataset[pd.isnull(users_dataset['Age'])].index,
inplace=True)

display(users_dataset.head(4))

       Gender  Age  Occupation Zip-code
UserID
1           F    1          10    48067
19          M    1          10    48073
51          F    1          10    10562
75          F    1          10    01748

       Gender   Age  Occupation Zip-code
UserID
1           F   NaN          10    48067
2           M  56.0          16    70072
3           M  25.0          15    55117
4           M  45.0           7    02460
5           M  25.0          20    55455
...       ...   ...         ...      ...
6036        F  25.0          15    32603
6037        F  45.0           1    76006
6038        F  56.0           1    14706
6039        F  45.0           0    01060
6040        M  25.0           6    11106

[6040 rows x 4 columns]

       Gender  Age  Occupation Zip-code
UserID
1           F  NaN          10    48067
19          M  NaN          10    48073
51          F  NaN          10    10562
75          F  NaN          10    01748

       Gender   Age  Occupation Zip-code
UserID
2           M  56.0          16    70072
3           M  25.0          15    55117
4           M  45.0           7    02460
5           M  25.0          20    55455

In [192]:
# Agrupar datos por atributos
display(users_dataset.groupby(by='Gender').describe())

           Age                                                     Occupation  \
         count       mean        std   min   25%   50%   75%   max      count
Gender
F       1631.0  32.287554  11.792015  18.0  25.0  25.0  45.0  56.0     1631.0
M       4187.0  31.568665  11.716053  18.0  25.0  25.0  35.0  56.0     4187.0


            mean       std  min  25%  50%   75%   max
Gender
F       6.498467  5.960285  0.0  1.0  4.0  11.0  20.0
M       8.743253  6.441753  0.0  4.0  7.0  15.0  20.0

In [193]:
# Grabar la tabla modificada
# Cambiar el separador a ','
# Guardar NaN como 'null'
ruta_output = os.path.join('res', 'ml-1m', 'o_users_processed.csv')
users_dataset.to_csv(ruta_output, sep=',',na_rep='null')

# Ejercicios

* Hacer un análisis general de los otros dos archivos CSV en ml-1m (‘movies.dat’ y ‘ratings.dat’)
* Analizando el dataset ratings.dat, ¿hay algún usuario que no tenga ninguna review? ¿Cuántos tienen menos de 30 reviews?

In [194]:
# especificar nombres, cargar sin cabecera
import os
import pandas as pd

ruta_ratings = os.path.join("res", "ml-1m", "ratings.dat")

# cargar datos de calificaciones
ratings_dataset = pd.read_csv(ruta_ratings, sep='::',
header=None, names=['UserID','MovieID','Rating','Timestamp'],
engine='python')

display(ratings_dataset)

         UserID  MovieID  Rating  Timestamp
0             1     1193       5  978300760
1             1      661       3  978302109
2             1      914       3  978301968
3             1     3408       4  978300275
4             1     2355       5  978824291
...         ...      ...     ...        ...
1000204    6040     1091       1  956716541
1000205    6040     1094       5  956704887
1000206    6040      562       5  956704746
1000207    6040     1096       4  956715648
1000208    6040     1097       4  956715569

[1000209 rows x 4 columns]

In [195]:
# hay algún usuario que no tenga ninguna review
n_users_with_reviews = len(ratings_dataset.groupby(by='UserID'))
print(n_users_with_reviews)

n_users = len(users_dataset)
print(n_users)

print(n_users - n_users_with_reviews)

6040
5818
-222

In [196]:
# Cuántos tienen menos de 30 reviews
ratings_under_30 = ratings_dataset.groupby(['UserID'])['UserID'].filter(lambda x: len(x) < 30).value_counts()

display(ratings_under_30)
print(len(ratings_under_30))

UserID
71      29
221     29
234     29
246     29
282     29
        ..
5533    20
5725    20
5828    20
5904    20
6038    20
Name: count, Length: 751, dtype: int64

751