![Logo ITQ](./img/logoitqv1.jpg)

Octavo Programa en Python

# Python 1, Estructura de datos, + Pandas

![Logo Python](./img/python_logo.png)

* Nombre: *Christian Zumárraga*
* Fecha : **9-07-2026**
* Repositorio: *[Link del repositorio de GitHub](https://github.com/Crishito/machine12026/blob/main/practicas/Python_Funciones.ipynb)*

In [23]:
# importar librerías para manejo de datos y operaciones numéricas
import pandas as pd
import numpy as np

In [24]:
# mostrar la versión de pandas instalada
pd.__version__

'3.0.3'

# Operaciones en pandas

**Búsqueda**

In [25]:
# crear una matriz aleatoria y convertirla en un DataFrame
rand_matrix = np.random.randint(6, size=(2,3))
frame = pd.DataFrame(rand_matrix, columns=list('ABC'))

display(frame)

   A  B  C
0  2  5  1
1  5  0  2

In [26]:
# buscando columnas (DataFrame como dic, busca en claves)
'A' in frame

True

In [27]:
# buscando valores
display(frame.isin([3,2])) # --> mask de respuesta (valores que son 3 o 2)

       A      B      C
0   True  False  False
1  False  False   True

In [28]:
# Contar el número de ocurrencias
print(frame.isin([4]).values.sum())

# devuelve una máscara con valores True si el elemento es 4
display(frame.isin([4]))

print(frame.isin([4]).values)

# pandas es una capa alrededor de numpy
type(frame.isin([4]).values)

0

       A      B      C
0  False  False  False
1  False  False  False

[[False False False]
 [False False False]]

numpy.ndarray

In [29]:
# Cuántos valores son >= 2
mask = frame >= 2
print(mask.values.sum())

display(mask)

4

      A      B      C
0  True   True  False
1  True  False   True

**Ordenación**

In [30]:
# crear una matriz aleatoria con índices mezclados
from random import shuffle

rand_matrix = np.random.randint(20, size=(5,4))

indices = list(range(5))
shuffle(indices) # mezcla indices

frame = pd.DataFrame(rand_matrix, columns=list('DACB'), index=indices)

display(frame)

    D   A   C   B
4  17  11   8  10
2   1   6   4  16
1  10   4  16   9
0   8  15  19  10
3   7  13  10   0

In [31]:
# ordenar por índice
display(frame.sort_index(ascending=False))
display(frame)

    D   A   C   B
4  17  11   8  10
3   7  13  10   0
2   1   6   4  16
1  10   4  16   9
0   8  15  19  10

    D   A   C   B
4  17  11   8  10
2   1   6   4  16
1  10   4  16   9
0   8  15  19  10
3   7  13  10   0

In [32]:
#ordenar por columna
display(frame.sort_index(axis=1, ascending=False))

    D   C   B   A
4  17   8  10  11
2   1   4  16   6
1  10  16   9   4
0   8  19  10  15
3   7  10   0  13

In [33]:
# ordenar filas por valor en columna
display(frame.sort_values(by='A', ascending=True))

    D   A   C   B
1  10   4  16   9
2   1   6   4  16
4  17  11   8  10
3   7  13  10   0
0   8  15  19  10

In [34]:
# ordenar columnas por valor en fila
display(frame.sort_values(by=1, axis=1, ascending=True))

    A   B   D   C
4  11  10  17   8
2   6  16   1   4
1   4   9  10  16
0  15  10   8  19
3  13   0   7  10

In [35]:
# ordenar por valor en columna y guardar cambios
frame.sort_values(by='A', ascending=False, inplace=True)
display(frame)

    D   A   C   B
0   8  15  19  10
3   7  13  10   0
4  17  11   8  10
2   1   6   4  16
1  10   4  16   9

**Ranking**
  
* Construir un ranking de valores

In [36]:
# mostrar el DataFrame
display(frame)

    D   A   C   B
0   8  15  19  10
3   7  13  10   0
4  17  11   8  10
2   1   6   4  16
1  10   4  16   9

In [37]:
# asignar rangos a los valores del DataFrame por fila
display(frame.rank(method='max', axis=1))

     D    A    C    B
0  1.0  3.0  4.0  2.0
3  2.0  4.0  3.0  1.0
4  4.0  3.0  1.0  2.0
2  1.0  3.0  2.0  4.0
1  3.0  1.0  4.0  2.0

In [38]:
# Imprimir los valores de la columna 'C' ordenados de mayor a menor
for x in frame.sort_values(by='C', ascending=False)['C'].values:
    print(x)

19
16
10
8
4

# Operaciones

Operaciones matemáticas entre objetos

In [39]:
# crear dos matrices aleatorias y convertirlas en DataFrames
matrixA = np.random.randint(100, size=(4,4))
matrixB = np.random.randint(100, size=(4,4))

frameA = pd.DataFrame(matrixA)
frameB = pd.DataFrame(matrixB)

display(frameA)
display(frameB)

    0   1   2   3
0   7  23  73   6
1  35  65   8  23
2  54  34  48  84
3  24  31  63  74

    0   1   2   3
0   1  70   8  41
1  80   0  63  37
2  76  65  78  86
3  84  33  46  21

In [40]:
# sumar DataFrames usando operadores y métodos
display(frameA + frameB == frameA.add(frameB))

display(frameA + frameB)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

     0   1    2    3
0    8  93   81   47
1  115  65   71   60
2  130  99  126  170
3  108  64  109   95

In [41]:
# restar DataFrames usando operadores y métodos
display(frameB - frameA == frameB.sub(frameA))

display(frameB - frameA)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

    0   1   2   3
0  -6  47 -65  35
1  45 -65  55  14
2  22  31  30   2
3  60   2 -17 -53

In [42]:
# si los DataFrames no son iguales, valor por defecto NaN
frameC = pd.DataFrame(np.random.randint(100, size=(3,3)))

display(frameA)
display(frameC)
display(frameC + frameA)

    0   1   2   3
0   7  23  73   6
1  35  65   8  23
2  54  34  48  84
3  24  31  63  74

    0   1   2
0  60  94  51
1  70  86  45
2  90  95   9

       0      1      2   3
0   67.0  117.0  124.0 NaN
1  105.0  151.0   53.0 NaN
2  144.0  129.0   57.0 NaN
3    NaN    NaN    NaN NaN

In [43]:
# especificar el valor por defecto con el argumento fill_value
display(frameA.add(frameC, fill_value=0))

       0      1      2     3
0   67.0  117.0  124.0   6.0
1  105.0  151.0   53.0  23.0
2  144.0  129.0   57.0  84.0
3   24.0   31.0   63.0  74.0

Operadores aritméticos solo válidos en elementos aceptables

In [44]:
# crear un DataFrame con valores de texto
frameD = pd.DataFrame({0: ['a','b'], 1: ['d','f']})

display(frameD)

# operación entre DataFrames con tipos incompatibles
# error al operar con DataFrames de tipos diferentes (números y texto)
frameA - frameD

   0  1
0  a  d
1  b  f

TypeError: operation 'rsub' not supported for dtype 'str' with dtype 'int32'

Operaciones entre Series y DataFrames

In [ ]:
# crear un DataFrame con valores aleatorios
rand_matrix = np.random.randint(10, size=(3, 4))

df = pd.DataFrame(rand_matrix, columns=list('ABCD'))

display(df)

display(df.iloc[0])
display(type(df.iloc[0]))

# restar una fila al resto del DataFrame
display(df - df.iloc[0])
display(df.sub(df.iloc[0], axis=1))

# restar por columnas
display(df.sub(df['A'], axis=0))

Pandas se basa en NumPy, np operadores binarios y unarios son aceptables

| Tipo | Operación | Descripción |
|------|-----------|-------------|
| Unario | *`abs`* | Valor absoluto de cada elemento |
| | *`sqrt`* | Raíz cuadrada de cada elemento |
| | *`exp`* | e^, siendo x cada elemento |
| | *`log`, `log10`, `log2`* | Logaritmos en distintas bases de cada elemento |
| | *`sign`* | Retorna el signo de cada elemento (-1 negativo, 0 cero, 1 positivo) |
| | *`ceil`* | Redondea cada elemento por arriba |
| | *`floor`* | Redondea cada elemento por abajo |
| | *`isnan`* | Retorna si cada elemento es NaN |
| | *`cos`, `sin`, `tan`* | Operaciones trigonométricas en cada elemento |
| | *`arccos`, `arcsin`, `arctan`* | Inversas de operaciones trigonométricas |
| Binario | *`add`* | Suma de dos arrays |
| | *`subtract`* | Resta de dos arrays |
| | *`multiply`* | Multiplicación de dos arrays |
| | *`divide`* | División de dos arrays |
| | *`maximum`, `minimum`* | Retorna el valor máximo/mínimo de cada pareja de elementos |
| | *`equal`, `not_equal`* | Retorna la comparación (igual o no igual) de cada pareja de elementos |
| | *`greater`, `greater_equal`, `less`, `less_equal`* | Retorna comparaciones (`>`, `>=`, `<`, `<=` respectivamente) de cada pareja de elementos |

Aplicación de funciones a medida con lambda

In [45]:
# Generación de una matriz aleatoria y creación de un DataFrame con nombres de columnas.
rand_matrix = np.random.randint(10, size=(3, 4))

frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)

# Aplicación de una función para obtener la diferencia entre el valor máximo y mínimo por fila.
print(frame.apply(lambda x: x.max() - x.min(), axis=1))

   A  B  C  D
0  1  4  1  6
1  1  4  7  5
2  2  5  9  1

0    5
1    6
2    8
dtype: int64

In [46]:
# Definición de una función para calcular la diferencia entre el valor máximo y mínimo.
def max_min(x):
    return x.max() - x.min()

# Aplicación de la función para obtener la diferencia por columna.
print(frame.apply(max_min, axis=0))

A    1
B    1
C    8
D    5
dtype: int64

In [47]:
# Generación de una matriz aleatoria y creación de un DataFrame para trabajar con sus datos.
rand_matrix = np.random.randint(10, size=(3, 4))

frame = pd.DataFrame(rand_matrix, columns=list('ABCD'))

display(frame)

# Cálculo de la diferencia entre el valor máximo y mínimo de cada fila.
print(frame.apply(lambda x: x.max() - x.min(), axis=1)) # diferencia por fila

   A  B  C  D
0  2  6  7  6
1  3  5  5  4
2  0  3  7  7

0    5
1    2
2    7
dtype: int64

# Estadística descriptiva

* Análisis preliminar de los datos
* Para Series y DataFrame

| Operación | Descripción |
| :--- | :--- |
| `count` | Número de valores no NaN |
| `describe` | Conjunto de estadísticas sumarias |
| `min`, `max` | Valores mínimo y máximo |
| `argmin`, `argmax` | Índices posicionales del valor mínimo y máximo |
| `idxmin`, `idxmax` | Índices semánticos del valor mínimo y máximo |
| `sum` | Suma de los elementos |
| `mean` | Media de los elementos |
| `median` | Mediana de los elementos |
| `mad` | Desviación absoluta media del valor medio |
| `var` | Varianza de los elementos |
| `std` | Desviación estándar de los elementos |
| `cumsum` | Suma acumulada de los elementos |
| `diff` | Diferencia aritmética de los elementos |

In [48]:
# Creación de un DataFrame a partir de un diccionario con información de personas.
diccionario = { 
    "nombre": ["Marisa", "Laura", "Manuel", "Carlos"], 
    "edad": [34, 34, 11, 30],
    "puntos": [98, 12, 98, np.nan], 
    "genero": ["F", "F", "M", "M"] 
}

frame = pd.DataFrame(diccionario)

display(frame)

# Visualización de estadísticas generales de los datos numéricos del DataFrame.
display(frame.describe()) # datos generales de elementos

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    34    12.0      F
2  Manuel    11    98.0      M
3  Carlos    30     NaN      M

            edad     puntos
count   4.000000   3.000000
mean   27.250000  69.333333
std    10.996211  49.652123
min    11.000000  12.000000
25%    25.250000  55.000000
50%    32.000000  98.000000
75%    34.000000  98.000000
max    34.000000  98.000000

In [49]:
# Operadores básicos para realizar cálculos sobre los datos del DataFrame.
print(frame.sum())

display(frame)

# Suma de los valores numéricos por cada fila del DataFrame.
print(frame.sum(axis=1, numeric_only=True))

nombre    MarisaLauraManuelCarlos
edad                          109
puntos                      208.0
genero                       FFMM
dtype: object

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    34    12.0      F
2  Manuel    11    98.0      M
3  Carlos    30     NaN      M

0    132.0
1     46.0
2    109.0
3     30.0
dtype: float64

In [50]:
# Cálculo del promedio de los valores numéricos del DataFrame.
frame.mean(numeric_only=True)

edad      27.250000
puntos    69.333333
dtype: float64

In [51]:
# Cálculo acumulativo de los valores del DataFrame.
frame.cumsum()

                    nombre  edad  puntos genero
0                   Marisa    34    98.0      F
1              MarisaLaura    68   110.0     FF
2        MarisaLauraManuel    79   208.0    FFM
3  MarisaLauraManuelCarlos   109     NaN   FFMM

In [52]:
# Conteo de valores disponibles en cada fila del DataFrame.
frame.count(axis=1)

0    4
1    4
2    4
3    3
dtype: int64

In [53]:
# Cálculo de la desviación estándar de una columna del DataFrame.
print(frame['edad'].std())

10.996211468804457

In [54]:
# Obtención del índice correspondiente al valor máximo de una columna del DataFrame.
frame['edad'].idxmax()

0

In [55]:
# Obtención del índice correspondiente al valor mínimo de una columna del DataFrame.
frame['puntos'].idxmin()

1

In [56]:
# Filtrado del DataFrame para obtener las filas que contienen los valores máximos de una columna.
print(frame['puntos'].max())

display(frame[frame['puntos'] == frame['puntos'].max()])

98.0

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
2  Manuel    11    98.0      M

In [57]:
# Creación de una nueva columna con la posición o ranking de los valores de una columna.
frame["ranking"] = frame["puntos"].rank(method='max')

In [58]:
# Visualización del DataFrame actualizado.
display(frame)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

## Agregaciones

In [59]:
# Visualización del DataFrame y agrupación de datos según una categoría.
display(frame)

df = frame.groupby('genero').count()

display(df)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

        nombre  edad  puntos  ranking
genero
F            2     2       2        2
M            2     2       1        1

In [60]:
# Agrupación de datos descartando valores nulos.
df = frame.groupby('puntos').count()

display(df)

        nombre  edad  genero  ranking
puntos
12.0         1     1       1        1
98.0         2     2       2        2

In [61]:
# Cálculo del promedio de los valores numéricos agrupados por una categoría.
display(frame.groupby('genero').mean(numeric_only=True))

        edad  puntos  ranking
genero
F       34.0    55.0      2.0
M       20.5    98.0      3.0

In [62]:
# Obtención de los valores máximos de los datos agrupados por una categoría.
display(frame.groupby('genero').max())

        nombre  edad  puntos  ranking
genero
F       Marisa    34    98.0      3.0
M       Manuel    30    98.0      3.0

In [63]:
# Aplicación de funciones de agregación para obtener diferentes estadísticas agrupadas.
display(frame.groupby('genero')[['edad', 'puntos']].aggregate(['min', 'mean', 'max']))

       edad           puntos
        min  mean max    min  mean   max
genero
F        34  34.0  34   12.0  55.0  98.0
M        11  20.5  30   98.0  98.0  98.0

In [64]:
# Filtrado de los datos agrupados según una condición determinada.
def media(x):
    return x["edad"].mean() > 30

display(frame)

frame.groupby('genero').filter(media)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0

## Correlaciones

pandas incluye métodos para analizar correlaciones - Relación matemática entre dos variables (-1 negativamente relacionadas, 1 positivamente relacionadas, 0 sin relación) - obj.corr(obj2) –> medida de correlación entre los datos de ambos objetos - https://blogs.oracle.com/ai-anddatascience/post/introduction-to-correlation

### Ejemplo Fuel efficiency

* https://archive.ics.uci.edu/ml/datasets/Auto+MPG

In [65]:
# Importación de Pandas y carga de un conjunto de datos externo en un DataFrame.
import pandas as pd

path = 'http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'

mpg_data = pd.read_csv(path, sep='\s+', header=None,
                       names=['mpg', 'cilindros', 'desplazamiento', 'potencia',
                              'peso', 'aceleracion', 'año', 'origen', 'nombre'],
                       na_values='?', engine='c')

In [66]:
# Visualización de una muestra aleatoria de registros del DataFrame.
display(mpg_data.sample(5))

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
164,21.0,6,231.0,110.0,3039.0,15.0,75,1,buick skyhawk
300,23.9,8,260.0,90.0,3420.0,22.2,79,1,oldsmobile cutlass salon brougham
122,24.0,4,121.0,110.0,2660.0,14.0,73,2,saab 99le
16,18.0,6,199.0,97.0,2774.0,15.5,70,1,amc hornet
123,20.0,6,156.0,122.0,2807.0,13.5,73,3,toyota mark ii

In [67]:
# Visualización de estadísticas generales incluyendo datos numéricos y categóricos.
display(mpg_data.describe(include='all'))

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000,398.000000,398
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ford pinto
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050,1.572864,NaN
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627,0.802055,NaN
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,1.000000,NaN
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000,1.000000,NaN
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000,1.000000,NaN
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000,2.000000,NaN
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,3.000000,NaN

In [68]:
# Visualización de la información general y estructura del DataFrame.
mpg_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   mpg             398 non-null    float64
 1   cilindros       398 non-null    int64
 2   desplazamiento  398 non-null    float64
 3   potencia        392 non-null    float64
 4   peso            398 non-null    float64
 5   aceleracion     398 non-null    float64
 6   año             398 non-null    int64
 7   origen          398 non-null    int64
 8   nombre          398 non-null    str
dtypes: float64(5), int64(3), str(1)
memory usage: 34.4 KB

### Correlaciones entre valores

In [69]:
# Cálculo de la correlación entre las variables numéricas del DataFrame.
mpg_data.corr(numeric_only=True)

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289,0.579267,0.563450
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419,-0.348746,-0.562543
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684,-0.370164,-0.609409
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196,-0.416361,-0.455171
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457,-0.306564,-0.581024
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000,0.288137,0.205873
año,0.579267,-0.348746,-0.370164,-0.416361,-0.306564,0.288137,1.000000,0.180662
origen,0.563450,-0.562543,-0.609409,-0.455171,-0.581024,0.205873,0.180662,1.000000

In [70]:
# Año y origen no parecen tener una relación significativa con las demás variables.
# Eliminación de columnas antes de calcular la matriz de correlación.
corr_data = mpg_data.drop(['año', 'origen'], axis=1).corr(numeric_only=True)

display(corr_data)

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000

In [71]:
# Importación de la librería para la creación de gráficos.
import matplotlib.pyplot as plt

In [72]:
# Representación gráfica de la matriz de correlación mediante una escala de colores.
corr_data.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1)

In [73]:
# Obtención de las variables con la correlación más negativa.
mpg_data.drop(['año', 'origen'], axis=1).corr(numeric_only=True).idxmin()

mpg                   peso
cilindros              mpg
desplazamiento         mpg
potencia               mpg
peso                   mpg
aceleracion       potencia
dtype: str

In [74]:
# Obtención de las variables con la correlación más positiva.
mpg_data.drop(['año', 'origen'], axis=1).corr(numeric_only=True).idxmax() # consigo misma....

mpg                          mpg
cilindros              cilindros
desplazamiento    desplazamiento
potencia                potencia
peso                        peso
aceleracion          aceleracion
dtype: str

In [76]:
# tabla similar con las correlaciones más positivas (evitar parejas del mismo valor)
positive_corr = mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True).copy()
np.fill_diagonal(positive_corr.values, 0)
display(positive_corr)
positive_corr.idxmax()

ValueError: underlying array is read-only

In [78]:
# Representación gráfica de la matriz de correlación mediante una escala de colores ajustada.
positive_corr.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1, vmin=-1.0, vmax=1.0)

## Ejercicios

* Ejercicios para practicar Pandas: https://github.com/ajcr/100-pandaspuzzles/blob/master/100-pandas-puzzles.ipynb